
name: PHPUnit

on:
  pull_request:

jobs:
  phpunit:
    name: WP ${{ matrix.wp-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.2']
        wp-versions: ['latest']
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v2

    - name: Install SVN
      run: sudo apt-get install subversion

    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 ${{ matrix.wp-versions }}

    - name: Mysql8 auth plugin workaround
      run: sudo mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: Unit tests
      run: composer test-unit

    - name: Integration tests
      run: composer test-integration  